[package]
edition.workspace = true
license.workspace = true
name = "recipe-stage0"
version = "0.1.1"

[dependencies]
hashlink = { workspace = true }
indexmap = { workspace = true }
itertools = { workspace = true }
marked-yaml = { workspace = true }
rattler-build = { workspace = true }
rattler_conda_types = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_yaml = { workspace = true }
url = { workspace = true }

[dev-dependencies]
insta = { workspace = true, features = ["yaml", "redactions", "filters"] }
