[workspace]
authors = ["Tim de Jager <tim@prefix.dev>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "pypi-source-deps"
platforms = ["osx-arm64", "linux-64", "win-64", "osx-64"]
version = "0.1.0"

[tasks]
hello = "python -c 'import minimal_project.module; minimal_project.module.hello()'"
start = { depends-on = ["hello"] }
test = "pytest ."

[dependencies]
python = "*"

[pypi-dependencies]
minimal-project = { path = "./minimal-project" }
setup-project = { path = "./setup-project" }
