[files]
extend-exclude = [
  ".git/",
  ".pixi/",
  ".claude/",
  "**/*.snap",
  "tests/data/mapping_files/*",
  "examples/**/**.ipynb",
  "robostack.yaml",
]
ignore-hidden = false

[default.extend-identifiers]
_placehold = "_placehold"
intoto = "intoto"
plt-setp = "plt.setp"
pn = "pn"
solvePnPRansac = "solvePnPRansac"
