[package]
authors = ["pixi contributors <hi@prefix.dev>"]
description = "Documentation binary that is used to generate documentation for pixi"
edition = "2021"
homepage = "https://github.com/prefix-dev/pixi"
license = "BSD-3-Clause"
name = "pixi_docs"
readme = "README.md"
repository = "https://github.com/prefix-dev/pixi"
version = "0.1.0"

[package.metadata.dist]
dist = false

[dependencies]
clap = { workspace = true }
fs-err = { workspace = true }
itertools = { workspace = true }
pixi_cli = { workspace = true, features = ["self_update"] }
rattler_conda_types = { workspace = true }
