[package]
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
name = "pixi_url"
readme.workspace = true
repository.workspace = true
version = "0.1.0"

[dependencies]
bzip2.workspace = true
dashmap = { workspace = true }
flate2.workspace = true
fs-err = { workspace = true, features = ["tokio"] }
futures.workspace = true
indicatif.workspace = true
pixi_record.workspace = true
pixi_spec.workspace = true
pixi_utils.workspace = true
rattler_digest.workspace = true
rattler_networking.workspace = true
reqwest = { workspace = true, features = ["stream"] }
reqwest-middleware.workspace = true
sevenz-rust2.workspace = true
tar.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
url.workspace = true
xz2.workspace = true
zip.workspace = true
zstd.workspace = true
