# --8<-- [start:minimal]
[workspace]
channels = ["https://prefix.dev/conda-forge"]
platforms = ["linux-64", "win-64", "osx-64", "osx-arm64"]
preview = ['pixi-build']

# --8<-- [start:package]
[package.build.backend]
name = "pixi-build-rust"
version = "0.4.*"

# --8<-- [end:minimal]
[package.build-dependencies]
cmake = "*"

[package.host-dependencies]
python = "*"

[package.run-dependencies]
bat = "*"
# --8<-- [end:package]

# --8<-- [start:dev]
[dev]
dev-package = { path = "." }
# --8<-- [end:dev]

[dependencies]
cargo-insta = "*"

[tasks]
build = "cargo build --release"
start = "cargo run"
test = "cargo test"
