[workspace]
channels = ["conda-forge"]
platforms = ["linux-64", "linux-aarch64", "win-64"]
preview = ["pixi-build"]                            # the feature is in preview

[workspace.build-variants]
cuda-version = [">=12.0,<13", ">=13.0,<14"]
python = ["3.14.*", "3.14.*"]

[feature.py314-cu13.dependencies]
cuda-version = ">=13.0,<14"
python = "3.14.*"

[feature.py314-cu12.dependencies]
cuda-version = ">=12.0,<13"
python = "3.14.*"

[environments]
py314-cu12 = { features = ["py314-cu13"] }
py314-cu13 = { features = ["py314-cu12"] }
