[project]
name = "reproduce"
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks.test_task]
cmd = "echo 'hello' > output.txt"

[tasks.alias_with_outputs]
depends-on = ["test_task"]
outputs = ["output.txt"]