# --8<-- [start:minimal]
[workspace]
channels = ["https://prefix.dev/conda-forge"]
name = "pytorch-conda-forge"
platforms = ["linux-64", "win-64"]

[system-requirements]
cuda = "12.0"

# --8<-- [start:cuda-version]
[dependencies]
pytorch-gpu = "*"
# --8<-- [end:minimal]
cuda-version = "12.6.*"
# --8<-- [end:cuda-version]
