[workspace]
authors = ["author"]
channels = ["conda-forge"]
name = "pixi-git"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.2,<3.15"

[pypi-dependencies]
# svgdigitizer = {git = "https://github.com/echemdb/svgdigitizer.git", rev = "master"}
ec-tools = { git = "https://github.com/echemdb/ec-tools.git", rev = "main" }
