[project]
dependencies = ["tqdm @ git+https://github.com/tqdm/tqdm.git"]
name = "test"

[build-system]
# requires = ["setuptools>=1.0.0"]
# build-backend = "poetry.core.masonry.api"
build-backend = "setuptools.build_meta"
requires = ["setuptools>=45", "wheel"]


[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["osx-arm64"]


[tool.pixi.dependencies]
numpy = "<=2.1"
