[workspace]
channels = ["https://prefix.dev/conda-forge"]
platforms = ["win-64", "linux-64", "osx-arm64", "osx-64"]
preview = ["pixi-build"]

[dependencies]
python_rich = { path = "." }

[tasks]
start = "rich-example-main"

[package]
name = "python_rich"
version = "0.1.0"

[package.build]
backend = { name = "pixi-build-python", version = "==0.3.2" }

[package.host-dependencies]
hatchling = "==1.26.3"

# --8<-- [start:run-dependencies]
[package.run-dependencies]
cpp_math = { path = "packages/cpp_math" }
rich = "13.9.*"
# --8<-- [end:run-dependencies]
