[package]
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
name = "pixi_manifest"
readme.workspace = true
repository.workspace = true
version = "0.1.0"

[dependencies]
indexmap = { workspace = true }
itertools = { workspace = true }
pep440_rs = { workspace = true }
pep508_rs = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde-untagged = { workspace = true }
serde_with = { workspace = true }
spdx = { workspace = true }
strsim = { workspace = true }
thiserror = { workspace = true }
toml_edit = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }

# Python specific dependencies, may require patches!
pyproject-toml = { workspace = true }

# Rattler crates
rattler_conda_types = { workspace = true }
rattler_lock = { workspace = true }
rattler_solve = { workspace = true, features = ["serde"] }
rattler_virtual_packages = { workspace = true }

# TODO: Remove these dependencies
miette = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
insta = { workspace = true, features = ["yaml"] }
rstest = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }
