[project]
authors = ["Nichita Morcotilo <nichita@prefix.dev>"]
channels = ["conda-forge", "robostack"]
name = "conda_mapping"
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]

conda-pypi-map = { "conda-forge" = "https://gist.githubusercontent.com/nichmor/fbd2d03d1ae4d8c950710a8918386211/raw/ffa191d09da63b599c733ec444dd47c123cb6c3d/custom_conda_forge_mapping.json", "robostack" = "robostack_mapping.json" }

[tasks]
start = { depends-on = ["test"] }
test = "python test_conda_mapping.py"

[dependencies]
boltons = "*"
jupyter-amphion = { version = "*", channel = "robostack" }
jupyter-ros = { version = "*", channel = "robostack" }
python = "~=3.11.0"
scipy = "~=1.11.4"

[pypi-dependencies]
black = { version = "~=23.10", extras = ["jupyter"] }

[system-requirements]
# Tensorflow on macOS arm64 requires macOS 12.0 or higher
macos = "12.0"
