[project]
name = "qgis"
version = "0.1.0"
description = "QGIS example with earthquake data"
authors = ["Ruben Arts <ruben@prefix.dev>"]
channels = ["conda-forge"]
platforms = ["linux-64", "win-64", "osx-64", "osx-arm64"]

[tasks]
get-data = "python get_data.py"
start = { cmd = "qgis earthquakes_example.qgz", depends_on = "get-data"}

[dependencies]
qgis = "3.32.1.*"
requests = "2.31.0.*"
geopandas = "0.13.2.*"
python = "3.11.4.*"
