[workspace]
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]
platforms = ["osx-arm64", "osx-64", "linux-64", "win-64"]
preview = ["pixi-build"]

# --8<-- [start:dependencies]
[dependencies]
cpp_math = { path = "packages/cpp_math" }
python_rich = { path = "." }
# --8<-- [end:dependencies]

# --8<-- [start:environments]
[feature.py311.dependencies]
python = "3.11.*"

[feature.py312.dependencies]
python = "3.12.*"

[environments]
py311 = ["py311"]
py312 = ["py312"]
# --8<-- [end:environments]


# --8<-- [start:variants]
[workspace.build-variants]
python = ["3.11.*", "3.12.*"]
# --8<-- [end:variants]


[tasks]
start = "rich-example-main"

[package]
name = "python_rich"
version = "0.1.0"

[package.build]
backend = { name = "pixi-build-python", version = "0.1.*" }

[package.host-dependencies]
hatchling = "==1.26.3"

[package.run-dependencies]
rich = ">=13.9.4,<14"
