[project]
name = "pypi-find-links"
authors = ["Tim de Jager <tim@prefix.dev>"]
channels = ["conda-forge"]
platforms = ["osx-arm64", "osx-64", "linux-64", "win-64"]
[project.pypi-options]
# This is similar to the --find-links option in pip
find-links = [{ path = "./links" }]

[tasks]
start = {depends-on = ["test"]}
test = "python -c 'import requests; print(requests.__version__)'"


# We need python to resolve pypi dependencies
[dependencies]
python = "3.12"

[pypi-dependencies]
# We should get this from the flat index
requests = "==2.31.0"
