[project]
name = "pypi-source-deps"
version = "0.1.0"
description = "Add a short description here"
authors = ["Tim de Jager <tim@prefix.dev>"]
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64", "win-64", "osx-64"]

[tasks]
hello = "python -c 'import minimal_project.module; minimal_project.module.hello()'"
test = "pytest ."

[dependencies]
python = "*"

[pypi-dependencies]

rich = "~=13.7"
# Lets start with some git dependencies
# With ssh
flask = { git = "ssh://git@github.com/pallets/flask" }
# With https
requests = { git = "https://github.com/psf/requests.git", rev = "0106aced5faa299e6ede89d1230bd6784f2c3660" }
# TODO: will support later -> or use branch = '' or tag = '' to specify a branch or tag

# You can also directly add a source dependency from file
minimal-project = { path = "./minimal-project", editable = true }

# You can also use a direct url, to either a `.tar.gz` or `.zip`, or a `.whl` file
click = { url = "https://github.com/pallets/click/releases/download/8.1.7/click-8.1.7-py3-none-any.whl" }

# You can also just the default git repo, it will checkout the default branch
pytest = { git = "https://github.com/pytest-dev/pytest.git"}
