[project]
channels = [
  "conda-forge",
  "conda-forge/label/cpptango_rc",
  "tango-controls/label/pytango_dev",
  "conda-forge/label/pytango_rc",
]
name = "itango"
platforms = ["osx-arm64"]

[dependencies]
ipython = ">=8.5,<10.0"
packaging = "*"
pip = "*"
pytango = ">=9.3.0"
python = ">=3.9"
qtconsole = "*"

[pypi-dependencies]
# itango = { path = ".", editable = true }
pytango = ">=9.3.0"

[feature.tangorc.dependencies]
cpptango = { version = "==10.1.1rc1", channel = "conda-forge/label/cpptango_rc" }
pytango = { version = "10.1.0dev3.*", channel = "tango-controls/label/pytango_dev" }
# pytango =  { version = "10.0.3rc1", channel = "conda-forge/label/pytango_rc" }

[feature.test.dependencies]
gevent = ">=25"
pytango-db = ">=0.4.1"
pytest = ">=8"
pytest-cov = "*"
tango-test = ">=3.11"

[feature.test.tasks]
test = "pytest"

[environments]
tangorc = ["tangorc", "test"]
