[project]
authors = ["Wolf Vollprecht <wolf@prefix.dev>"]
channels = ["conda-forge"]
description = "Example how to get started with flask in a pixi environment."
name = "flask-hello-world"
platforms = ["linux-64", "win-64", "osx-64", "osx-arm64"]
version = "0.1.0"
preview = ["pixi-build"]

[tasks]
start = "python -m flask run --port=5050"

[dependencies]
flask = "2.*"

[build-system]
build-backend = "pixi-build-python"
channels = [
  "https://fast.prefix.dev/pixi-build-backends",
  "https://fast.prefix.dev/conda-forge",
]
dependencies = ["pixi-build-python"]
