[workspace]
channels = ["https://prefix.dev/conda-forge"]
platforms = ["osx-arm64", "linux-64", "osx-64", "win-64"]
preview = ["pixi-build"]                                  # (1)!

[dependencies] # (2)!
cpp_math = { path = "." }
python = "*"

[tasks]
start = "python -c 'import cpp_math as b; print(b.add(1, 2))'" # (3)!

[package] # (4)!
name = "cpp_math"
version = "0.1.0"

[package.build]
backend = { name = "pixi-build-cmake", version = "0.3.*" }

[package.build.config]
extra-args = ["-DCMAKE_BUILD_TYPE=Release"] # (9)!

[package.host-dependencies]
cmake = "3.20.*"   # (8)!
nanobind = "2.4.*" # (6)!
python = "3.12.*"  # (7)!
