# --8<-- [start:minimal]
[project]
name = "pytorch-conda-forge"

[tool.pixi.project]
channels = ["https://prefix.dev/conda-forge"]
platforms = ["linux-64"]

[tool.pixi.system-requirements]
cuda = "12.0"

# --8<-- [start:cuda-version]
[tool.pixi.dependencies]
pytorch-gpu = "*"
# --8<-- [end:minimal]
cuda-version = "12.6.*"
# --8<-- [end:cuda-version]
