[package]
authors.workspace = true
description = "This crate defines the default system requirements"
edition.workspace = true
homepage.workspace = true
license.workspace = true
name = "pixi_default_sys"
readme.workspace = true
repository.workspace = true
version = "0.1.0"

[dependencies]
rattler_conda_types = { workspace = true }
