# --8<-- [start:full]
# Specifies properties for the whole workspace
# --8<-- [start:preview]
[workspace]
preview = ["pixi-build"]
# --8<-- [end:preview]
channels = ["https://prefix.dev/conda-forge"]
platforms = ["win-64", "linux-64", "osx-arm64", "osx-64"]

# There can be multiple packages in a workspace
# In `package` you specify properties specific to the package
# --8<-- [start:package]
[package]
name = "simple_python"
version = "0.1.0"
# --8<-- [end:package]

# Here the build system of the package is specified
# We are using `pixi-build-python` in order to build a Python package
# --8<-- [start:build-system]
[package.build.backend]
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]
name = "pixi-build-python"
version = "0.1.*"
# --8<-- [end:build-system]


# The Python package `simple_python` uses `hatchling` as Python build backend
# --8<-- [start:host-dependencies]
[package.host-dependencies]
hatchling = "*"
# --8<-- [end:host-dependencies]

# --8<-- [start:dependencies]
# We add our package as dependency to the workspace
[dependencies]
simple_python = { path = "." }
# pixi also support git dependencies
boost-check = { git = "https://github.com/wolfv/pixi-build-examples", branch = "main", subdirectory = "boost-check" }
# --8<-- [end:dependencies]

# --8<-- [start:run-dependencies]
[package.run-dependencies]
rich = ">=13.9.4,<14"
# --8<-- [end:run-dependencies]

# --8<-- [end:full]
