[workspace]
channels = ["https://prefix.dev/conda-forge"]
platforms = ["osx-arm64", "osx-64", "linux-64", "win-64"]
preview = ["pixi-build"]

[dependencies]
cpp_math = { path = "." }
python = "3.12.*"

[tasks]
start = "python -c 'import cpp_math as b; print(b.add(1, 2))'"

[package]
name = "cpp_math"
version = "0.1.0"

[package.build]
backend = { name = "pixi-build-rattler-build", version = "0.3.*" }
