[project]
authors = [{ name = "nichmor", email = "nmorkotilo@gmail.com" }]
dependencies = ["tqdm"]
name = "jora"
# requires-python = ">= 3.11"
version = "0.1.0"

[tool.uv.sources]
tqdm = { git = "https://github.com/tqdm/tqdm.git", rev = "a2d5f1c9d1cbdbcf56f52dc4365ea4124e3e33f7" }


[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=45", "wheel"]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tool.pixi.pypi-dependencies]
jora = { path = ".", editable = true }

[tool.pixi.tasks]
