[package]
authors.workspace = true
description = "Conversion between pixi and uv types"
edition.workspace = true
homepage.workspace = true
license.workspace = true
name = "pixi_uv_conversions"
readme.workspace = true
repository.workspace = true
version = "0.1.0"


[dependencies]
dashmap = { workspace = true }
dunce = { workspace = true }
once_cell = { workspace = true }
pep508_rs = { workspace = true }
pixi_manifest = { workspace = true }
rattler_lock = { workspace = true }
thiserror = { workspace = true }
url = { workspace = true }
uv-configuration = { workspace = true }
uv-distribution-filename = { workspace = true }
uv-distribution-types = { workspace = true }
uv-git = { workspace = true }
uv-normalize = { workspace = true }
uv-pep440 = { workspace = true }
uv-pep508 = { workspace = true, features = ["non-pep508-extensions"] }
uv-pypi-types = { workspace = true }
uv-python = { workspace = true }
uv-types = { workspace = true }
