[package]
authors.workspace = true
description = "Conversion between pixi and uv types"
edition.workspace = true
homepage.workspace = true
license.workspace = true
name = "pixi_uv_conversions"
readme.workspace = true
repository.workspace = true
version = "0.1.0"


[dependencies]
chrono = { workspace = true }
dunce = { workspace = true }
jiff = { workspace = true }
miette = { workspace = true }
pep440_rs = { workspace = true }
pep508_rs = { workspace = true }
pixi_git = { workspace = true }
pixi_manifest = { workspace = true }
pixi_pypi_spec = { workspace = true }
pixi_record = { workspace = true }
pixi_spec = { workspace = true }
rattler_lock = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
uv-configuration = { workspace = true }
uv-distribution-filename = { workspace = true }
uv-distribution-types = { workspace = true }
uv-git-types = { workspace = true }
uv-normalize = { workspace = true }
uv-pep440 = { workspace = true }
uv-pep508 = { workspace = true, features = ["non-pep508-extensions"] }
uv-pypi-types = { workspace = true }
uv-python = { workspace = true }
uv-redacted = { workspace = true }
uv-resolver = { workspace = true }
uv-types = { workspace = true }
