[workspace]
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]
platforms = ["osx-arm64", "osx-64", "linux-64", "win-64"]
preview = ["pixi-build"]

[dependencies]
python_bindings = { path = "." }

[tasks]
start = "python -c 'import python_bindings as b; print(b.add(1, 2))'"

[package]
name = "python_bindings"
version = "0.1.0"

[package.build]
backend = { name = "pixi-build-cmake", version = "~=0.1.0" }

# --8<-- [start:host-dependencies]
[package.host-dependencies]
cmake = ">=3.20, <3.27"
nanobind = ">=2.4.0, <2.5.0"
python = "*"                 # (1)!
# --8<-- [end:host-dependencies]
