[project]
name = "pypi"
version = "0.1.0"
description = "Add a short description here"
authors = ["Bas Zalmstra <bas@prefix.dev>"]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]


[activation]
scripts = ["activate.sh"]

[tasks]
start = "python pycosat_example.py"
test = "python pycosat_example.py"

[dependencies]
python = "~=3.11.0"
numpy = "*"
libclang = "~=16.0.6"
scipy = "~=1.11.4"

[pypi-dependencies]
pyboy = "==1.6.6"
tensorflow = "==2.14.0"
flask = "*"
black = {version = "~=23.10", extras = ["jupyter"]}
# sdists:
pyliblzfse = "*"
pycosat = "*"
plot-antenna = "==1.7"
env_test_package = "==0.0.3"

[system-requirements]
# Tensorflow on macOS arm64 requires macOS 12.0 or higher
macos = "12.0"
